server:
  port: 8091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db?serverTimezone=UTC
    username: postgres
    password: adminpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-db:5432/user_db
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8765/eureka/
